py_binary(
    name = "create_dataset",
    srcs = ["create_dataset.py"],
    srcs_version = "PY2AND3",
    visibility = ["//amt/pip:__subpackages__"],
    deps = [
        "//amt",
        # tensorflow dep
        # librosa dep
        # numpy dep
    ],
)